version: '3.8'

services:
  merchandise-service:
    build: "merchandise-service/"
    hostname: merchandise-service
    image: "merchandise-service:local"
    ports:
      - "8080:80"
    depends_on:
      - redis

  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    hostname: stock-api
    ports:
      - "8081:80"
    depends_on:
      - redis

  emailing-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
    hostname: emailing-service
    ports:
      - "8082:80"
    depends_on:
      - redis

  employees-service :
    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
    hostname: employees-service
    ports:
      - "8083:80"
    depends_on:
      - redis

  supply-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
    hostname: supply-service
    ports:
      - "8084:80"
    depends_on:
      - redis
  
  redis:
    image: redis
    hostname: redis
